# -*- coding: utf-8 -*-
"""mean_meadian_standard_deviation_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BS1LwOMEDS_glXbggRqlbNPV_xdOesc9
"""

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

class DataAnalyzer:
    def __init__(self, data):
        self.data = np.array(data)

    def calculate_statistics(self):
        mean = np.mean(self.data)
        median = np.median(self.data)
        std_dev = np.std(self.data)
        return mean, median, std_dev

def main():
    try:
        data = list(map(float, input("Enter a list of numbers separated by space: ").split()))
        analyzer = DataAnalyzer(data)
        mean, median, std_dev = analyzer.calculate_statistics()

        print("Mean:", mean)
        print("Median:", median)
        print("Standard Deviation:", std_dev)

        # Generate and plot a histogram
        plt.hist(data, bins=10, alpha=0.7, color='b', label='Data')
        plt.axvline(mean, color='red', linestyle='dashed', linewidth=1, label='Mean')
        plt.legend()
        plt.title("Data Distribution")
        plt.xlabel("Value")
        plt.ylabel("Frequency")
        plt.show()

    except ValueError:
        print("Invalid input. Please enter a list of numbers.")
    except Exception as e:
        print("An error occurred:", str(e))

if __name__ == "__main__":
    main()

