# -*- coding: utf-8 -*-
"""DL1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ExRZohEs4iDB6Qkk7iWzJnLq6pQ80sGH
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer

model_name = 'gpt2'
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
def autocorrect_html(html_code):
    prompt = "Correct the following HTML code strictly without adding your content. Remove incorrect HTML:\n\n"
    prompt += html_code
    n = len(html_code) + 100
    input_ids = tokenizer.encode(prompt, return_tensors='pt', max_length=n, truncation=True, padding=True)
    corrected_ids = model.generate(input_ids, max_length=n, num_return_sequences=1, temperature=0.34, do_sample=True, pad_token_id=tokenizer.eos_token_id)
    corrected_html = tokenizer.decode(corrected_ids[0], skip_special_tokens=True)

    return corrected_html
html_code_with_issues = """
<html>
<head>
    <title>My Web Page</title>
</head>
<body>
    <H1>
"""
corrected_html = autocorrect_html(html_code_with_issues)
print("Original HTML:")
print(html_code_with_issues)
print("\nCorrected HTML:")
print(corrected_html)